w3c/ift-encoder

js_client/patch_subset_client.cc
Following https://w3c.github.io/IFT/Overview.html#handling-patch-response the response should contain a 4 byte magic number at the start.
=> Update client to expect magic number

WORKSPACE, patch_subset/BUILD, patch_subset/client_server_integration_test.cc, patch_subset/patch_subset_server_impl.cc, patch_subset/patch_subset_server_impl.h, patch_subset/patch_subset_server_impl_test.cc, patch_subset/server_integration_test.cc, patch_subset/vcdiff_binary_diff.cc, patch_subset/vcdiff_binary_diff.h, patch_subset/vcdiff_binary_patch.cc, patch_subset/vcdiff_binary_patch.h, patch_subset/vcdiff_patching_test.cc, third_party/open-vcdiff.BUILD, third_party/open-vcdiff/BUILD, third_party/open-vcdiff/config.h
The spec requires all implementations to support at least VCDIFF as a patch format. This adds support for VCDIFF in addition to the currently used brotli diff.
=> Add support for patches using VCDIFF

patch_subset/patch_subset_client.cc, patch_subset/patch_subset_client_test.cc, patch_subset/patch_subset_server_impl.cc, patch_subset/patch_subset_server_impl_test.cc
Prior to this change encoded indices were being placed into codepoints_have/needed of the request. The spec calls for these to be placed in the indices_have/needed fields instead.
=> Update client and server to use indices_have/needed fields of PatchRequest.

patch_subset/patch_subset_client.cc, patch_subset/patch_subset_client_test.cc, patch_subset/patch_subset_server_impl.cc, patch_subset/patch_subset_server_impl.h, patch_subset/patch_subset_server_impl_test.cc, patch_subset/server_integration_test.cc
Updates the server implementation to be inline with the well formed requirements for requests in the spec.
=> Reject requests that are missing required checksums or protocol version.

brotli/BUILD, brotli/brotli_font_diff.cc, brotli/brotli_font_diff.h, brotli/brotli_font_diff_test.cc, brotli/brotli_stream.cc, brotli/brotli_stream.h, brotli/brotli_stream_test.cc, brotli/glyf_differ.h, brotli/hmtx_differ.h, brotli/loca_differ.h, brotli/table_differ.h, brotli/table_range.h, patch_subset/bit_output_buffer.cc, patch_subset/sparse_bit_set.cc, util/precompress-test.cc
Update the custom diffing mechanism to take an list of differs, one per table. Each per table differ is a state machine that instructs the diff driver how to construct the ranges of bytes that are existing and new data. Currently differs are implemented for glyf, loca, hmtx, and vmtx.
=> BrotliFontDiff add support for diffing loca, hmtx, and vmtx.

js_client/patch_subset_client.cc, patch_subset/encodings.h, patch_subset/patch_subset_client_test.cc, patch_subset/patch_subset_server_impl.cc, patch_subset/patch_subset_server_impl.h, patch_subset/patch_subset_server_impl_test.cc
This matches the proposed shared brotli content encoding value in https://github.com/WICG/compression-dictionary-transport
=> Use 'sbr' instead of 'brdiff' for content encoding.

common/BUILD, common/font_helper.cc, common/font_helper.h, common/font_helper_test.cc, ift/BUILD, ift/encoder/encoder.cc, ift/iftb_binary_patch.cc, ift/integration_test.cc
The current IFTB patch merging implementation doesn't support changing loca len, so for now update the encoder to keep it constant. Also expands tests to cover this case and check glyph presence in addition to codepoint presence.
=> Update encoder to ensure loca length stays the same in mixed mode.

WORKSPACE, fontations/Cargo.lock, ift/client/fontations_client.cc, ift/client/fontations_client.h, ift/integration_test.cc, ift/table_keyed_diff.cc, ift/table_keyed_diff_test.cc, third_party/fontations.BUILD
Uses fontations ift extension command line utility to simulate the client in the integration tests. The test suite currently demonstrates successful integration of mixed mode (glyph + table keyed) encoding use optional features and design space.
=> Reenable integration tests using the fontations rust client.

MODULE.bazel, common/font_helper.cc, common/font_helper.h, fontations/Cargo.lock, ift/client/fontations_client.cc, ift/client/fontations_client.h, ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/encoder/encoder_test.cc, ift/integration_test.cc, util/font2ift.cc
Previously we always forced long loca to avoid dealing with potential loca type change. Now if the fully expanded font will fit into a short loca the encoder will use it.
=> Allow encoder to use short loca when possible.

MODULE.bazel, common/hb_set_unique_ptr.cc, common/hb_set_unique_ptr.h, fontations/Cargo.lock, ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/encoder/encoder_test.cc, ift/encoder/glyph_segmentation.cc, ift/encoder/glyph_segmentation.h, ift/integration_test.cc, ift/proto/format_2_patch_map.cc, ift/proto/format_2_patch_map_test.cc, ift/proto/ift_table_test.cc, ift/proto/patch_map.cc, ift/proto/patch_map.h, ift/proto/patch_map_test.cc, util/convert_iftb.cc, util/convert_iftb_test.cc, util/encoder_config.proto, util/font2ift.cc, util/glyph_keyed_segments.cc
This PR adds support for configuring the encoder with generic activation conditions for glyph keyed patches. Conditions can be of the form if (p1 or ... or ...) and (...) and ... then load pn. The previously available functionality for optional features has been reworked to use the new general framework.
Additionally serialization support has been added for writing a patch map using activation conditions via the child entry indices mechanism (see: https://github.com/w3c/IFT/pull/252).
Lastly, this PR also updates the glyph segmentation util to make use of the new condition functionality in the test encodings it produces.
=> Activation conditions and child entry indices

common/hb_set_unique_ptr.cc, common/hb_set_unique_ptr.h, ift/encoder/BUILD, ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/encoder/encoder_test.cc, ift/encoder/glyph_segmentation.cc, ift/encoder/glyph_segmentation.h, ift/encoder/glyph_segmentation_test.cc, ift/glyph_keyed_diff.h, ift/integration_test.cc, util/BUILD, util/glyph_keyed_segmenter.cc, util/glyph_keyed_segments.cc
Base patches are those that contain glyphs exclusive to the codepoints that map to them. This PR adds support for automatically merging these together to meet a configured minimum patch size. The merger use dependency information from the conditional patches activation rules to find base patches that are likely to interact and uses those as candidates for merging. This reduces the overall number of conditional patches needed which ultimately reduces overhead.
Support for merging conditional patches together is not yet implemented.
=> In the glyph keyed segmenter implement merging of base patches

MODULE.bazel, fontations/Cargo.lock, ift/client/fontations_client.cc, ift/client/fontations_client.h, ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/encoder/encoder_test.cc, ift/integration_test.cc, third_party/fontations.BUILD
The check to detect when we transitioned between different design space configurations was incorrect which resulted in all table keyed patches in a font with design space extension including a patch against gvar. This fixes the check and adds a unit test which catches the issue.
=> Bug fix: don't include gvar in all table keyed patches.

common/font_helper.cc, common/font_helper.h, common/font_helper_test.cc, ift/proto/format_2_patch_map.cc, ift/proto/format_2_patch_map.h, ift/proto/format_2_patch_map_test.cc, ift/proto/ift_table.cc, ift/proto/ift_table_test.cc
Matches the spec changes in https://github.com/w3c/IFT/pull/265, https://github.com/w3c/IFT/issues/260
=> Add CFF/CFF2 charstring offsets to encoded fonts.

MODULE.bazel, third_party/harfbuzz.BUILD, third_party/harfbuzz/BUILD, third_party/harfbuzz/hb-features.h, util/end-to-end.sh
Generates an ift font from a config, extends it for a given text sample, and then compares the resutls of shaping/rendering the original and extended version.
=> Add an end to end testing shell script.

common/BUILD, common/int_set.h, common/int_set_test.cc
Also supports being used as a key and value in absl collection classes (btree_set/map, flat_hash_set/map). This will allow more broad usage of hb set's throughout the encoder code and avoid having to change back and forth between absl collection types and hb_set's.
=> Create a wrapper around hb_set_t, IntSet, that acts like a standard collection class.

ift/encoder/closure_glyph_segmenter.cc, ift/encoder/glyph_segmentation.cc, ift/encoder/glyph_segmentation.h, ift/encoder/glyph_segmentation_test.cc
Glyphs can be removed from a condition if additional conditions are detected. If all glyphs are removed from a condition then the condition should be removed.
=> [closure segmenter] remove conditions that become empty.

ift/encoder/BUILD, ift/encoder/closure_glyph_segmenter.cc, ift/encoder/closure_glyph_segmenter_test.cc, ift/encoder/glyph_segmentation.cc, ift/encoder/glyph_segmentation.h
This refactors the closure segmenter implmentation to allow for incremental updates on glyph groupings after applying a segment merge. Prior to this change after each merge all glyph groupings would be fully recalculated from scratch, which results in O(N^2) like runtime.
By doing incremental updates we significantly reduce the amount of work performed since only things affected by the merge  are recomputed on each iteration resulting in O(N) like runtime instead.
In an example test, the total time for computing the Noto Serif SC segmentation in the [IFT demo](https://github.com/garretrieger/ift-demo/blob/main/Makefile#L78) (which starts with segments of one codepoint each) went from 2m15s to 45s. In this test case profiling shows that after this change computation is now primarily …
=> [closure segmenter] Add incremental glyph grouping to the closure segmenter merging loop.

ift/encoder/closure_glyph_segmenter.cc
This implements the following two changes to significantly speed up the run time of the closure segmenter:
1.  Brotli compression (used to estimated patch sizes) accounts for most of the time spent in the analysis. Reduce brotli quality from 9  to 8. Reduces run time of analysis of Noto Serif SC from approximately 45s -> 3s.
2. Track which segments are inert (non interacting). When merging a set of segments that are all inert we can bypass closure analysis on the new segment and form the new glyph set by unioning the exclusive gids from the merged segments. This roughly halves the number of closure calls in an example analysis of Noto Serif SC. Only a minor improvement to runtime, as the closure cost is dwarfed by brotli compression cost.
=> [closure segmenter] Further speed up the closure segmenter run time.

MODULE.bazel, fontations/Cargo.lock, ift/client/fontations_client.cc, ift/client/fontations_client.h, ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/encoder/encoder_test.cc, ift/integration_test.cc, ift/proto/format_2_patch_map.cc, ift/proto/format_2_patch_map_test.cc, ift/proto/patch_map.cc, ift/proto/patch_map.h, third_party/fontations.BUILD, util/encoder_config.proto, util/font2ift.cc
Updates the encoder to match this spec change: https://github.com/w3c/IFT/pull/262
=> Implement patch preload lists in the encoder

ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/integration_test.cc, util/font2ift.cc
Automatically disables glyf transformations in woff2 when needed as noted in https://w3c.github.io/IFT/Overview.html#ift-and-compression.
=> In font2ift by default output a woff2 encoded font with an option to disable.

MODULE.bazel, fontations/Cargo.lock, ift/encoder/encoder.cc, ift/encoder/encoder.h, ift/integration_test.cc
Design space changes require the glyph keyed patch map to be rewritten (since the glyph keyed patches in use are changed to match the new design space). Since the glyph keyed compat id is changed full invalidation is needed. Concretely this prevents unnecessary preloads for glyph keyed patches that can't be used after the design space change.
=> Use full invalidation (instead of partial) patches when modifying design space.

MODULE.bazel, docs/experimental/compiler.md, ift/encoder/BUILD, ift/encoder/closure_glyph_segmenter.cc, ift/encoder/closure_glyph_segmenter_test.cc, ift/encoder/compiler.cc, ift/encoder/compiler.h, ift/encoder/compiler_test.cc, ift/feature_registry/BUILD, ift/feature_registry/feature_registry_test.cc, ift/feature_registry/registry_to_cc.py, ift/integration_test.cc, ift/proto/BUILD, ift/proto/patch_map.cc
Fixes https://github.com/w3c/ift-encoder/issues/106. Pull in the feature registry from the spec repository and include the default features in compiled IFT font's initial subset definition.
=> Use IFT spec default feature registry.

common/int_set.h, common/int_set_test.cc, common/woff2.cc, common/woff2.h, common/woff2_test.cc, ift/encoder/candidate_merge.cc, ift/encoder/candidate_merge.h, ift/encoder/closure_glyph_segmenter.cc, ift/encoder/closure_glyph_segmenter.h, ift/encoder/closure_glyph_segmenter_test.cc, ift/encoder/glyph_groupings.h, ift/encoder/merge_strategy.h, ift/encoder/requested_segmentation_information.cc, ift/encoder/requested_segmentation_information.h, ift/encoder/segmentation_context.h, util/closure_glyph_keyed_segmenter_util.cc
It's common that there are segments with 100% probabiliity, since these are always needed they can be moved to the initial font to make them available immediately. This adds an optional check (enabled via --init_font_merge_threshold) to find segments which give cost reductions larger than the threshold and move them into the initial font.
This step happens prior to merge processing since init font changes potentially affect all segments.
=> In closure segmenter optionally check for segments that can be merged into the initial font.

ift/encoder/candidate_merge.cc, ift/encoder/closure_glyph_segmenter.cc, ift/encoder/closure_glyph_segmenter_test.cc, ift/encoder/glyph_groupings.cc, ift/encoder/glyph_groupings.h, ift/encoder/glyph_segmentation.cc, ift/encoder/glyph_segmentation.h, ift/encoder/segmentation_context.cc
Prior to this change exclusive glyphs were being kep in the 'and glyph' groupings and down stream users needed to know that 'and glyph' groupings of size 1 are exclusive patches. This change moves exclusive groupings to their own map to make it clear and reduce the need for special casing in various other places.
=> Refactor GlyphGroupings to use separate exclusive glyphs grouping.
